[project]
name = "financial-projection-app-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.3.0",
    "streamlit>=1.49.1",
    "pandas",
    "numpy",
    "scipy",
    "openpyxl",
]
